# Docker Compose file for CRM System

services:
  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crm_system
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crm_system.sql:/docker-entrypoint-initdb.d/crm_system.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network
    # Add performance tuning for MySQL
    command: --innodb-buffer-pool-size=256M --max-connections=200
    # Add resource limits for MySQL
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      # Add build args for better caching
      args:
        - NODE_ENV=production
    environment:
      - DATABASE_URL=mysql://root:1234@mysql:3306/crm_system
      - DATABASE_HOST=mysql
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1024
    # Use bind mounts only for development, not needed for production
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    container_name: nextjs
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 512M
    # Add healthcheck for nextjs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine # Use alpine for smaller image
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - nextjs
    networks:
      - app-network
    # Add resource limits for nginx
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}