version: '3.8'

services:
  mysql:
    image: mariadb:10.5
    container_name: crm-mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crm_system
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crm_system.sql:/docker-entrypoint-initdb.d/crm_system.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - crm-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-nextjs
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:1234@mysql:3306/crm_system
      - DATABASE_HOST=mysql
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - crm-network
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin-prod
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - crm-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
    depends_on:
      - nextjs
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local