version: '3.8'

services:
  nextjs:
    container_name: crm_app
    build:
      context: .
      dockerfile: Dockerfile.optimized
      args:
        NODE_ENV: production
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://ahmadreza-avandi.ir
      - NEXTAUTH_URL=https://ahmadreza-avandi.ir
    networks:
      - crm_network

networks:
  crm_network:
    name: crm_network
