version: '3.8'

services:
  mysql:
    image: mariadb:10.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-1234}
      MYSQL_DATABASE: ${DATABASE_NAME:-crm_system}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crm_system.sql:/docker-entrypoint-initdb.d/crm_system.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD:-1234}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      - DATABASE_URL=mysql://root:${DATABASE_PASSWORD:-1234}@mysql:3306/${DATABASE_NAME:-crm_system}
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-1234}
      - DATABASE_NAME=${DATABASE_NAME:-crm_system}
      - NODE_ENV=production
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.example.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER:-your-email@example.com}
      - EMAIL_PASS=${EMAIL_PASS:-your-password}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-client-id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-your-client-secret}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN:-your-refresh-token}
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf.template
      - ./nginx/nginx.sh:/docker-entrypoint.d/40-nginx-config.sh
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nextjs
    networks:
      - app-network
    command: /bin/bash -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-1234}
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}