version: '3.8'

services:
  nextjs-build:
    build:
      context: .
      dockerfile: Dockerfile.staged
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS="--max-old-space-size=2048"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G