version: '3.8'

services:
  # دیتابیس MySQL
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crm_system
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crm_system.sql:/docker-entrypoint-initdb.d/crm_system.sql
    ports:
      - "3306:3306"
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js اپلیکیشن
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crm-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=crm_system
      - DATABASE_URL=mysql://root:1234@mysql:3306/crm_system
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - crm-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  mysql_data: