version: '3.8'

services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VPS_MODE: "true"
    container_name: crm-nextjs
    env_file:
      - .env
    environment:
      VPS_MODE: "true"
      ENABLE_AUDIO: "true"
      NEXT_PUBLIC_AUDIO_BACKEND: "true"
      NODE_ENV: production
    volumes:
      - ./audio-temp:/app/audio-temp
      - ./public:/app/public
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - crm-network

  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crm-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: crm-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - crm-network

  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./public:/usr/share/nginx/html
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - crm-network

volumes:
  mysql_data:
  certbot_data:
  certbot_www:

networks:
  crm-network:
    driver: bridge
