version: '3.8'

services:
  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crm_system
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crm_system.sql:/docker-entrypoint-initdb.d/crm_system.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network

  nextjs:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "apk add --no-cache git && npm install && npm run build && npm start"
    environment:
      - DATABASE_URL=mysql://root:1234@mysql:3306/crm_system
      - DATABASE_HOST=mysql
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=2048
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    container_name: nextjs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}
  node_modules_volume: {}