version: '3.8'

services:
  mysql:
    image: mariadb:10.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crm_system
    volumes:
      - mysql_data:/var/lib/mysql
      - ./crm_system.sql:/docker-entrypoint-initdb.d/crm_system.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      - DATABASE_URL=mysql://root:1234@mysql:3306/crm_system
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=crm_system
      - NODE_ENV=development
      # Email and OAuth settings should be configured in .env.local file
      # Example:
      # - EMAIL_HOST=smtp.example.com
      # - EMAIL_PORT=587
      # - EMAIL_USER=your-email@example.com
      # - EMAIL_PASS=your-password
      # - GOOGLE_CLIENT_ID=your-client-id
      # - GOOGLE_CLIENT_SECRET=your-client-secret
      # - GOOGLE_REFRESH_TOKEN=your-refresh-token
      # - DOMAIN_NAME=your-domain.com
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./:/app/src
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}
